---

version: "3.2"
services:
  db:
    image: "mysql:5.7"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
      MYSQL_DATABASE: bqgen
      BIND-ADDRESS: '0.0.0.0'
      TZ: "Asia/Tokyo"
    networks:
      - app
networks:
  app:
